// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBprggiW92Ye245lnEkzwCk49ykkKIVr5c',
    appId: '1:624999351167:web:d3737491ebf93fb725504a',
    messagingSenderId: '624999351167',
    projectId: 'lively-fe3be',
    authDomain: 'lively-fe3be.firebaseapp.com',
    storageBucket: 'lively-fe3be.appspot.com',
    measurementId: 'G-LXLN3CZFRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFUTVgEXdmmPTHjgEcufW9RQS2ENq0coA',
    appId: '1:624999351167:android:2b64427f589ca3e325504a',
    messagingSenderId: '624999351167',
    projectId: 'lively-fe3be',
    storageBucket: 'lively-fe3be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmL2cTnC2v0l9Nuvqr86MdvO8EoUF-bE0',
    appId: '1:624999351167:ios:6c8c5eac3e93ac0d25504a',
    messagingSenderId: '624999351167',
    projectId: 'lively-fe3be',
    storageBucket: 'lively-fe3be.appspot.com',
    iosClientId: '624999351167-vrvoimm0tbckkuju18mi4uo4a8728o8u.apps.googleusercontent.com',
    iosBundleId: 'li.lively.app.studio.livelyStudio',
  );
}
